### ISSUE TITLE
Novas rotas de usuário

### ISSUE THREAD

**Issue by jardely** [marcosbmf/devweb#5]
Minha sugestão é criar as rotas para remover o usuário para o caso que ele não queira mais ter a conta, e criar a rota que retorne um usuário. 
Também faço a sugestão de melhorar a organização do seu backend, criando controllers  ao invés de colocar toda a lógica no arquivo de rotas.

**Comment by marcosbmf** [comment]
Gerenciamento de usuários retirado da V1.
